env:
  - GOPROXY=https://proxy.golang.org,direct
before:
  hooks:
    - make deps
    - make assets
builds:
  - env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
    main: ./cmd/rocket/main.go
    id: rocket
    binary: rocket
    targets:
      - darwin_amd64
      - darwin_arm64
      - windows_amd64
      - windows_arm_6
      - windows_386
      - linux_amd64
      - linux_arm_7
      - linux_arm64
      - linux_386
      - android_arm64
  - env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
    main: ./cmd/rocketd/main.go
    id: rocketd
    binary: rocketd
    targets:
      - darwin_amd64
      - darwin_arm64
      - windows_amd64
      - windows_arm_7
      - windows_386
      - linux_amd64
      - linux_arm_7
      - linux_arm64
      - linux_386
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
archives:
  - id: rocketd
    builds:
      - rocketd
    name_template: "rocketd_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    replacements:
      darwin: MacOS
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
    format_overrides:
      - goos: windows
        format: zip
  - id: rocket
    builds:
      - rocket
    name_template: "rocket_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    replacements:
      darwin: MacOS
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
    format_overrides:
      - goos: windows
        format: zip
brews:
  - name: rocket
    ids:
      - rocket
    tap:
      owner: arthur
      name: homebrew-tap
    commit_author:
      name: Arthur Kalikiti
      email: arthurkalikiti@gmail.com
    folder: Formula
    homepage: "https://github.com/arthurkay/rocket"
    description: "Introspected tunnels to localhost a fork from rocket."
    install: |
      bin.install "rocket"
    test: |
      system "#{bin}/rocket", "-v"
  - name: rocketd
    ids:
      - rocketd
    tap:
      owner: arthur
      name: homebrew-tap
    commit_author:
      name: Arthur Kalikiti
      email: arthurkalikiti@gmail.com
    folder: Formula
    homepage: "https://github.com/arthurkay/rocket"
    description: "Server introspected tunnels to localhost a fork from rocket."
    install: |
      bin.install "rocketd"
    test: |
      system "#{bin}/rocketd", "-v"
scoop:
  bucket:
    owner: arthur
    name: scoop-bucket
  commit_author:
    name: Arthur Kalikiti
    email: arthurkalikiti@gmail.com
  homepage: "https://github.com/arthurkay/rocket"
  description: "Introspected tunnels to localhost a fork from rocket."
  license: MIT
nfpms:
  - id: rocket
    homepage: "https://github.com/arthurkay/rocket"
    description: "Introspected tunnels to localhost a fork from rocket."
    maintainer: Arthur Kalikiti <arthurkalikiti@gmail.com>
    license: MIT
    formats:
      - deb
      - rpm
    recommends:
      - rpm
    builds:
      - rocket
      - rocketd