on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

name: Release

jobs:
  release:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1
      - uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - name: Install Deps
        run: |
          sudo apt install -y make
          go get -u golang.org/x/lint/golint
          go get -u github.com/jteeuwen/go-bindata/go-bindata
          git checkout -f
      - uses: goreleaser/goreleaser-action@v2
        with:
          distribution: goreleaser
          version: latest
          args: release --auto-snapshot
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          